QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    Box2D/Collision/Shapes/b2ChainShape.cpp \
    Box2D/Collision/Shapes/b2CircleShape.cpp \
    Box2D/Collision/Shapes/b2EdgeShape.cpp \
    Box2D/Collision/Shapes/b2PolygonShape.cpp \
    Box2D/Collision/b2BroadPhase.cpp \
    Box2D/Collision/b2CollideCircle.cpp \
    Box2D/Collision/b2CollideEdge.cpp \
    Box2D/Collision/b2CollidePolygon.cpp \
    Box2D/Collision/b2Collision.cpp \
    Box2D/Collision/b2Distance.cpp \
    Box2D/Collision/b2DynamicTree.cpp \
    Box2D/Collision/b2TimeOfImpact.cpp \
    Box2D/Common/b2BlockAllocator.cpp \
    Box2D/Common/b2Draw.cpp \
    Box2D/Common/b2Math.cpp \
    Box2D/Common/b2Settings.cpp \
    Box2D/Common/b2StackAllocator.cpp \
    Box2D/Common/b2Timer.cpp \
    Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp \
    Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp \
    Box2D/Dynamics/Contacts/b2CircleContact.cpp \
    Box2D/Dynamics/Contacts/b2Contact.cpp \
    Box2D/Dynamics/Contacts/b2ContactSolver.cpp \
    Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp \
    Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp \
    Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp \
    Box2D/Dynamics/Contacts/b2PolygonContact.cpp \
    Box2D/Dynamics/Joints/b2DistanceJoint.cpp \
    Box2D/Dynamics/Joints/b2FrictionJoint.cpp \
    Box2D/Dynamics/Joints/b2GearJoint.cpp \
    Box2D/Dynamics/Joints/b2Joint.cpp \
    Box2D/Dynamics/Joints/b2MotorJoint.cpp \
    Box2D/Dynamics/Joints/b2MouseJoint.cpp \
    Box2D/Dynamics/Joints/b2PrismaticJoint.cpp \
    Box2D/Dynamics/Joints/b2PulleyJoint.cpp \
    Box2D/Dynamics/Joints/b2RevoluteJoint.cpp \
    Box2D/Dynamics/Joints/b2RopeJoint.cpp \
    Box2D/Dynamics/Joints/b2WeldJoint.cpp \
    Box2D/Dynamics/Joints/b2WheelJoint.cpp \
    Box2D/Dynamics/b2Body.cpp \
    Box2D/Dynamics/b2ContactManager.cpp \
    Box2D/Dynamics/b2Fixture.cpp \
    Box2D/Dynamics/b2Island.cpp \
    Box2D/Dynamics/b2World.cpp \
    Box2D/Dynamics/b2WorldCallbacks.cpp \
    Box2D/HelloWorld/HelloWorld.cpp \
    Box2D/Rope/b2Rope.cpp \
    Box2D/Testbed/Framework/Main.cpp \
    Box2D/Testbed/Framework/Render.cpp \
    Box2D/Testbed/Framework/Test.cpp \
    Box2D/Testbed/Tests/TestEntries.cpp \
    Box2D/freeglut/freeglut_callbacks.c \
    Box2D/freeglut/freeglut_cursor.c \
    Box2D/freeglut/freeglut_display.c \
    Box2D/freeglut/freeglut_ext.c \
    Box2D/freeglut/freeglut_font.c \
    Box2D/freeglut/freeglut_font_data.c \
    Box2D/freeglut/freeglut_gamemode.c \
    Box2D/freeglut/freeglut_geometry.c \
    Box2D/freeglut/freeglut_glutfont_definitions.c \
    Box2D/freeglut/freeglut_init.c \
    Box2D/freeglut/freeglut_input_devices.c \
    Box2D/freeglut/freeglut_joystick.c \
    Box2D/freeglut/freeglut_main.c \
    Box2D/freeglut/freeglut_menu.c \
    Box2D/freeglut/freeglut_misc.c \
    Box2D/freeglut/freeglut_overlay.c \
    Box2D/freeglut/freeglut_spaceball.c \
    Box2D/freeglut/freeglut_state.c \
    Box2D/freeglut/freeglut_stroke_mono_roman.c \
    Box2D/freeglut/freeglut_stroke_roman.c \
    Box2D/freeglut/freeglut_structure.c \
    Box2D/freeglut/freeglut_teapot.c \
    Box2D/freeglut/freeglut_videoresize.c \
    Box2D/freeglut/freeglut_window.c \
    Box2D/glui/algebra3.cpp \
    Box2D/glui/arcball.cpp \
    Box2D/glui/glui.cpp \
    Box2D/glui/glui_add_controls.cpp \
    Box2D/glui/glui_bitmap_img_data.cpp \
    Box2D/glui/glui_bitmaps.cpp \
    Box2D/glui/glui_button.cpp \
    Box2D/glui/glui_checkbox.cpp \
    Box2D/glui/glui_column.cpp \
    Box2D/glui/glui_commandline.cpp \
    Box2D/glui/glui_control.cpp \
    Box2D/glui/glui_edittext.cpp \
    Box2D/glui/glui_filebrowser.cpp \
    Box2D/glui/glui_list.cpp \
    Box2D/glui/glui_listbox.cpp \
    Box2D/glui/glui_mouse_iaction.cpp \
    Box2D/glui/glui_node.cpp \
    Box2D/glui/glui_panel.cpp \
    Box2D/glui/glui_radio.cpp \
    Box2D/glui/glui_rollout.cpp \
    Box2D/glui/glui_rotation.cpp \
    Box2D/glui/glui_scrollbar.cpp \
    Box2D/glui/glui_separator.cpp \
    Box2D/glui/glui_spinner.cpp \
    Box2D/glui/glui_statictext.cpp \
    Box2D/glui/glui_string.cpp \
    Box2D/glui/glui_textbox.cpp \
    Box2D/glui/glui_translation.cpp \
    Box2D/glui/glui_tree.cpp \
    Box2D/glui/glui_treepanel.cpp \
    Box2D/glui/glui_window.cpp \
    Box2D/glui/quaternion.cpp \
    main.cpp \
    mainwindow.cpp \
    model.cpp

HEADERS += \
    Box2D/Box2D.h \
    Box2D/Collision/Shapes/b2ChainShape.h \
    Box2D/Collision/Shapes/b2CircleShape.h \
    Box2D/Collision/Shapes/b2EdgeShape.h \
    Box2D/Collision/Shapes/b2PolygonShape.h \
    Box2D/Collision/Shapes/b2Shape.h \
    Box2D/Collision/b2BroadPhase.h \
    Box2D/Collision/b2Collision.h \
    Box2D/Collision/b2Distance.h \
    Box2D/Collision/b2DynamicTree.h \
    Box2D/Collision/b2TimeOfImpact.h \
    Box2D/Common/b2BlockAllocator.h \
    Box2D/Common/b2Draw.h \
    Box2D/Common/b2GrowableStack.h \
    Box2D/Common/b2Math.h \
    Box2D/Common/b2Settings.h \
    Box2D/Common/b2StackAllocator.h \
    Box2D/Common/b2Timer.h \
    Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h \
    Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h \
    Box2D/Dynamics/Contacts/b2CircleContact.h \
    Box2D/Dynamics/Contacts/b2Contact.h \
    Box2D/Dynamics/Contacts/b2ContactSolver.h \
    Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h \
    Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h \
    Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h \
    Box2D/Dynamics/Contacts/b2PolygonContact.h \
    Box2D/Dynamics/Joints/b2DistanceJoint.h \
    Box2D/Dynamics/Joints/b2FrictionJoint.h \
    Box2D/Dynamics/Joints/b2GearJoint.h \
    Box2D/Dynamics/Joints/b2Joint.h \
    Box2D/Dynamics/Joints/b2MotorJoint.h \
    Box2D/Dynamics/Joints/b2MouseJoint.h \
    Box2D/Dynamics/Joints/b2PrismaticJoint.h \
    Box2D/Dynamics/Joints/b2PulleyJoint.h \
    Box2D/Dynamics/Joints/b2RevoluteJoint.h \
    Box2D/Dynamics/Joints/b2RopeJoint.h \
    Box2D/Dynamics/Joints/b2WeldJoint.h \
    Box2D/Dynamics/Joints/b2WheelJoint.h \
    Box2D/Dynamics/b2Body.h \
    Box2D/Dynamics/b2ContactManager.h \
    Box2D/Dynamics/b2Fixture.h \
    Box2D/Dynamics/b2Island.h \
    Box2D/Dynamics/b2TimeStep.h \
    Box2D/Dynamics/b2World.h \
    Box2D/Dynamics/b2WorldCallbacks.h \
    Box2D/Rope/b2Rope.h \
    Box2D/Testbed/Framework/Render.h \
    Box2D/Testbed/Framework/Test.h \
    Box2D/Testbed/Tests/AddPair.h \
    Box2D/Testbed/Tests/ApplyForce.h \
    Box2D/Testbed/Tests/BodyTypes.h \
    Box2D/Testbed/Tests/Breakable.h \
    Box2D/Testbed/Tests/Bridge.h \
    Box2D/Testbed/Tests/BulletTest.h \
    Box2D/Testbed/Tests/Cantilever.h \
    Box2D/Testbed/Tests/Car.h \
    Box2D/Testbed/Tests/Chain.h \
    Box2D/Testbed/Tests/CharacterCollision.h \
    Box2D/Testbed/Tests/CollisionFiltering.h \
    Box2D/Testbed/Tests/CollisionProcessing.h \
    Box2D/Testbed/Tests/CompoundShapes.h \
    Box2D/Testbed/Tests/Confined.h \
    Box2D/Testbed/Tests/ContinuousTest.h \
    Box2D/Testbed/Tests/ConvexHull.h \
    Box2D/Testbed/Tests/ConveyorBelt.h \
    Box2D/Testbed/Tests/DistanceTest.h \
    Box2D/Testbed/Tests/Dominos.h \
    Box2D/Testbed/Tests/DumpShell.h \
    Box2D/Testbed/Tests/DynamicTreeTest.h \
    Box2D/Testbed/Tests/EdgeShapes.h \
    Box2D/Testbed/Tests/EdgeTest.h \
    Box2D/Testbed/Tests/Gears.h \
    Box2D/Testbed/Tests/Mobile.h \
    Box2D/Testbed/Tests/MobileBalanced.h \
    Box2D/Testbed/Tests/MotorJoint.h \
    Box2D/Testbed/Tests/OneSidedPlatform.h \
    Box2D/Testbed/Tests/Pinball.h \
    Box2D/Testbed/Tests/PolyCollision.h \
    Box2D/Testbed/Tests/PolyShapes.h \
    Box2D/Testbed/Tests/Prismatic.h \
    Box2D/Testbed/Tests/Pulleys.h \
    Box2D/Testbed/Tests/Pyramid.h \
    Box2D/Testbed/Tests/RayCast.h \
    Box2D/Testbed/Tests/Revolute.h \
    Box2D/Testbed/Tests/Rope.h \
    Box2D/Testbed/Tests/RopeJoint.h \
    Box2D/Testbed/Tests/SensorTest.h \
    Box2D/Testbed/Tests/ShapeEditing.h \
    Box2D/Testbed/Tests/SliderCrank.h \
    Box2D/Testbed/Tests/SphereStack.h \
    Box2D/Testbed/Tests/TheoJansen.h \
    Box2D/Testbed/Tests/Tiles.h \
    Box2D/Testbed/Tests/TimeOfImpact.h \
    Box2D/Testbed/Tests/Tumbler.h \
    Box2D/Testbed/Tests/VaryingFriction.h \
    Box2D/Testbed/Tests/VaryingRestitution.h \
    Box2D/Testbed/Tests/VerticalStack.h \
    Box2D/Testbed/Tests/Web.h \
    Box2D/freeglut/freeglut.h \
    Box2D/freeglut/freeglut_ext.h \
    Box2D/freeglut/freeglut_internal.h \
    Box2D/freeglut/freeglut_std.h \
    Box2D/freeglut/freeglut_teapot_data.h \
    Box2D/glui/algebra3.h \
    Box2D/glui/arcball.h \
    Box2D/glui/glui.h \
    Box2D/glui/glui_internal.h \
    Box2D/glui/glui_internal_control.h \
    Box2D/glui/quaternion.h \
    mainwindow.h \
    model.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    Box2D/Box2DConfig.cmake \
    Box2D/Build/Readme.txt \
    Box2D/Build/vs2012/Box2D.sln \
    Box2D/Build/vs2012/Box2D.vcxproj \
    Box2D/Build/vs2012/Box2D.vcxproj.filters \
    Box2D/Build/vs2012/FreeGLUT.vcxproj \
    Box2D/Build/vs2012/FreeGLUT.vcxproj.filters.xml \
    Box2D/Build/vs2012/GLUI.vcxproj \
    Box2D/Build/vs2012/GLUI.vcxproj.filters.xml \
    Box2D/Build/vs2012/HelloWorld.vcxproj \
    Box2D/Build/vs2012/HelloWorld.vcxproj.filters.xml \
    Box2D/Build/vs2012/Testbed.vcxproj \
    Box2D/Build/vs2012/Testbed.vcxproj.filters \
    Box2D/Build/xcode5/Box2D.xcodeproj/project.pbxproj \
    Box2D/Build/xcode5/Box2D.xcodeproj/project.xcworkspace/contents.xcworkspacedata.xml \
    Box2D/Building.txt \
    Box2D/CMakeLists.txt \
    Box2D/Changes.txt \
    Box2D/Documentation/API/html/_box2_d_8h_source.html \
    Box2D/Documentation/API/html/annotated.html \
    Box2D/Documentation/API/html/b2_block_allocator_8h_source.html \
    Box2D/Documentation/API/html/b2_body_8h_source.html \
    Box2D/Documentation/API/html/b2_broad_phase_8h_source.html \
    Box2D/Documentation/API/html/b2_chain_and_circle_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_chain_and_polygon_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_chain_shape_8h_source.html \
    Box2D/Documentation/API/html/b2_circle_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_circle_shape_8h_source.html \
    Box2D/Documentation/API/html/b2_collision_8h.html \
    Box2D/Documentation/API/html/b2_collision_8h_source.html \
    Box2D/Documentation/API/html/b2_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_contact_manager_8h_source.html \
    Box2D/Documentation/API/html/b2_contact_solver_8h_source.html \
    Box2D/Documentation/API/html/b2_distance_8h_source.html \
    Box2D/Documentation/API/html/b2_distance_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_draw_8h_source.html \
    Box2D/Documentation/API/html/b2_dynamic_tree_8h_source.html \
    Box2D/Documentation/API/html/b2_edge_and_circle_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_edge_and_polygon_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_edge_shape_8h_source.html \
    Box2D/Documentation/API/html/b2_fixture_8h_source.html \
    Box2D/Documentation/API/html/b2_friction_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_gear_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_growable_stack_8h_source.html \
    Box2D/Documentation/API/html/b2_island_8h_source.html \
    Box2D/Documentation/API/html/b2_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_math_8h_source.html \
    Box2D/Documentation/API/html/b2_motor_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_mouse_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_polygon_and_circle_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_polygon_contact_8h_source.html \
    Box2D/Documentation/API/html/b2_polygon_shape_8h_source.html \
    Box2D/Documentation/API/html/b2_prismatic_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_pulley_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_revolute_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_rope_8h_source.html \
    Box2D/Documentation/API/html/b2_rope_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_settings_8h.html \
    Box2D/Documentation/API/html/b2_settings_8h_source.html \
    Box2D/Documentation/API/html/b2_shape_8h_source.html \
    Box2D/Documentation/API/html/b2_stack_allocator_8h_source.html \
    Box2D/Documentation/API/html/b2_time_of_impact_8h_source.html \
    Box2D/Documentation/API/html/b2_time_step_8h_source.html \
    Box2D/Documentation/API/html/b2_timer_8h_source.html \
    Box2D/Documentation/API/html/b2_weld_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_wheel_joint_8h_source.html \
    Box2D/Documentation/API/html/b2_world_8h_source.html \
    Box2D/Documentation/API/html/b2_world_callbacks_8h_source.html \
    Box2D/Documentation/API/html/bc_s.png \
    Box2D/Documentation/API/html/bdwn.png \
    Box2D/Documentation/API/html/classb2_block_allocator-members.html \
    Box2D/Documentation/API/html/classb2_block_allocator.html \
    Box2D/Documentation/API/html/classb2_body-members.html \
    Box2D/Documentation/API/html/classb2_body.html \
    Box2D/Documentation/API/html/classb2_broad_phase-members.html \
    Box2D/Documentation/API/html/classb2_broad_phase.html \
    Box2D/Documentation/API/html/classb2_chain_and_circle_contact-members.html \
    Box2D/Documentation/API/html/classb2_chain_and_circle_contact.html \
    Box2D/Documentation/API/html/classb2_chain_and_circle_contact.png \
    Box2D/Documentation/API/html/classb2_chain_and_polygon_contact-members.html \
    Box2D/Documentation/API/html/classb2_chain_and_polygon_contact.html \
    Box2D/Documentation/API/html/classb2_chain_and_polygon_contact.png \
    Box2D/Documentation/API/html/classb2_chain_shape-members.html \
    Box2D/Documentation/API/html/classb2_chain_shape.html \
    Box2D/Documentation/API/html/classb2_chain_shape.png \
    Box2D/Documentation/API/html/classb2_circle_contact-members.html \
    Box2D/Documentation/API/html/classb2_circle_contact.html \
    Box2D/Documentation/API/html/classb2_circle_contact.png \
    Box2D/Documentation/API/html/classb2_circle_shape-members.html \
    Box2D/Documentation/API/html/classb2_circle_shape.html \
    Box2D/Documentation/API/html/classb2_circle_shape.png \
    Box2D/Documentation/API/html/classb2_contact-members.html \
    Box2D/Documentation/API/html/classb2_contact.html \
    Box2D/Documentation/API/html/classb2_contact.png \
    Box2D/Documentation/API/html/classb2_contact_filter-members.html \
    Box2D/Documentation/API/html/classb2_contact_filter.html \
    Box2D/Documentation/API/html/classb2_contact_listener-members.html \
    Box2D/Documentation/API/html/classb2_contact_listener.html \
    Box2D/Documentation/API/html/classb2_contact_manager-members.html \
    Box2D/Documentation/API/html/classb2_contact_manager.html \
    Box2D/Documentation/API/html/classb2_contact_solver-members.html \
    Box2D/Documentation/API/html/classb2_contact_solver.html \
    Box2D/Documentation/API/html/classb2_destruction_listener-members.html \
    Box2D/Documentation/API/html/classb2_destruction_listener.html \
    Box2D/Documentation/API/html/classb2_distance_joint-members.html \
    Box2D/Documentation/API/html/classb2_distance_joint.html \
    Box2D/Documentation/API/html/classb2_distance_joint.png \
    Box2D/Documentation/API/html/classb2_draw-members.html \
    Box2D/Documentation/API/html/classb2_draw.html \
    Box2D/Documentation/API/html/classb2_dynamic_tree-members.html \
    Box2D/Documentation/API/html/classb2_dynamic_tree.html \
    Box2D/Documentation/API/html/classb2_edge_and_circle_contact-members.html \
    Box2D/Documentation/API/html/classb2_edge_and_circle_contact.html \
    Box2D/Documentation/API/html/classb2_edge_and_circle_contact.png \
    Box2D/Documentation/API/html/classb2_edge_and_polygon_contact-members.html \
    Box2D/Documentation/API/html/classb2_edge_and_polygon_contact.html \
    Box2D/Documentation/API/html/classb2_edge_and_polygon_contact.png \
    Box2D/Documentation/API/html/classb2_edge_shape-members.html \
    Box2D/Documentation/API/html/classb2_edge_shape.html \
    Box2D/Documentation/API/html/classb2_edge_shape.png \
    Box2D/Documentation/API/html/classb2_fixture-members.html \
    Box2D/Documentation/API/html/classb2_fixture.html \
    Box2D/Documentation/API/html/classb2_friction_joint-members.html \
    Box2D/Documentation/API/html/classb2_friction_joint.html \
    Box2D/Documentation/API/html/classb2_friction_joint.png \
    Box2D/Documentation/API/html/classb2_gear_joint-members.html \
    Box2D/Documentation/API/html/classb2_gear_joint.html \
    Box2D/Documentation/API/html/classb2_gear_joint.png \
    Box2D/Documentation/API/html/classb2_growable_stack-members.html \
    Box2D/Documentation/API/html/classb2_growable_stack.html \
    Box2D/Documentation/API/html/classb2_island-members.html \
    Box2D/Documentation/API/html/classb2_island.html \
    Box2D/Documentation/API/html/classb2_joint-members.html \
    Box2D/Documentation/API/html/classb2_joint.html \
    Box2D/Documentation/API/html/classb2_joint.png \
    Box2D/Documentation/API/html/classb2_motor_joint-members.html \
    Box2D/Documentation/API/html/classb2_motor_joint.html \
    Box2D/Documentation/API/html/classb2_motor_joint.png \
    Box2D/Documentation/API/html/classb2_mouse_joint-members.html \
    Box2D/Documentation/API/html/classb2_mouse_joint.html \
    Box2D/Documentation/API/html/classb2_mouse_joint.png \
    Box2D/Documentation/API/html/classb2_polygon_and_circle_contact-members.html \
    Box2D/Documentation/API/html/classb2_polygon_and_circle_contact.html \
    Box2D/Documentation/API/html/classb2_polygon_and_circle_contact.png \
    Box2D/Documentation/API/html/classb2_polygon_contact-members.html \
    Box2D/Documentation/API/html/classb2_polygon_contact.html \
    Box2D/Documentation/API/html/classb2_polygon_contact.png \
    Box2D/Documentation/API/html/classb2_polygon_shape-members.html \
    Box2D/Documentation/API/html/classb2_polygon_shape.html \
    Box2D/Documentation/API/html/classb2_polygon_shape.png \
    Box2D/Documentation/API/html/classb2_prismatic_joint-members.html \
    Box2D/Documentation/API/html/classb2_prismatic_joint.html \
    Box2D/Documentation/API/html/classb2_prismatic_joint.png \
    Box2D/Documentation/API/html/classb2_pulley_joint-members.html \
    Box2D/Documentation/API/html/classb2_pulley_joint.html \
    Box2D/Documentation/API/html/classb2_pulley_joint.png \
    Box2D/Documentation/API/html/classb2_query_callback-members.html \
    Box2D/Documentation/API/html/classb2_query_callback.html \
    Box2D/Documentation/API/html/classb2_ray_cast_callback-members.html \
    Box2D/Documentation/API/html/classb2_ray_cast_callback.html \
    Box2D/Documentation/API/html/classb2_revolute_joint-members.html \
    Box2D/Documentation/API/html/classb2_revolute_joint.html \
    Box2D/Documentation/API/html/classb2_revolute_joint.png \
    Box2D/Documentation/API/html/classb2_rope-members.html \
    Box2D/Documentation/API/html/classb2_rope.html \
    Box2D/Documentation/API/html/classb2_rope_joint-members.html \
    Box2D/Documentation/API/html/classb2_rope_joint.html \
    Box2D/Documentation/API/html/classb2_rope_joint.png \
    Box2D/Documentation/API/html/classb2_shape-members.html \
    Box2D/Documentation/API/html/classb2_shape.html \
    Box2D/Documentation/API/html/classb2_shape.png \
    Box2D/Documentation/API/html/classb2_stack_allocator-members.html \
    Box2D/Documentation/API/html/classb2_stack_allocator.html \
    Box2D/Documentation/API/html/classb2_timer-members.html \
    Box2D/Documentation/API/html/classb2_timer.html \
    Box2D/Documentation/API/html/classb2_weld_joint-members.html \
    Box2D/Documentation/API/html/classb2_weld_joint.html \
    Box2D/Documentation/API/html/classb2_weld_joint.png \
    Box2D/Documentation/API/html/classb2_wheel_joint-members.html \
    Box2D/Documentation/API/html/classb2_wheel_joint.html \
    Box2D/Documentation/API/html/classb2_wheel_joint.png \
    Box2D/Documentation/API/html/classb2_world-members.html \
    Box2D/Documentation/API/html/classb2_world.html \
    Box2D/Documentation/API/html/classes.html \
    Box2D/Documentation/API/html/closed.png \
    Box2D/Documentation/API/html/dir_2b0aaca8962b4c18f14a1e758f920130.html \
    Box2D/Documentation/API/html/dir_2bb440aa7e31c6a1fa7299279b8cd0fb.html \
    Box2D/Documentation/API/html/dir_54cad791c4d2b04cb4a0ba0bba686f79.html \
    Box2D/Documentation/API/html/dir_6d0481e1d3c0616ecae75ec35bddf767.html \
    Box2D/Documentation/API/html/dir_a7f953fea4e008d17e00594b3bbaff29.html \
    Box2D/Documentation/API/html/dir_b4ce54b79b9fedd1c216c802993ffbe1.html \
    Box2D/Documentation/API/html/dir_f938a2b4566b4bd7e1dc8e6edc30956c.html \
    Box2D/Documentation/API/html/dir_fe69815ec5df867d8480807c50df8353.html \
    Box2D/Documentation/API/html/doxygen.css \
    Box2D/Documentation/API/html/doxygen.png \
    Box2D/Documentation/API/html/dynsections.js \
    Box2D/Documentation/API/html/files.html \
    Box2D/Documentation/API/html/ftv2blank.png \
    Box2D/Documentation/API/html/ftv2cl.png \
    Box2D/Documentation/API/html/ftv2doc.png \
    Box2D/Documentation/API/html/ftv2folderclosed.png \
    Box2D/Documentation/API/html/ftv2folderopen.png \
    Box2D/Documentation/API/html/ftv2lastnode.png \
    Box2D/Documentation/API/html/ftv2link.png \
    Box2D/Documentation/API/html/ftv2mlastnode.png \
    Box2D/Documentation/API/html/ftv2mnode.png \
    Box2D/Documentation/API/html/ftv2mo.png \
    Box2D/Documentation/API/html/ftv2node.png \
    Box2D/Documentation/API/html/ftv2ns.png \
    Box2D/Documentation/API/html/ftv2plastnode.png \
    Box2D/Documentation/API/html/ftv2pnode.png \
    Box2D/Documentation/API/html/ftv2splitbar.png \
    Box2D/Documentation/API/html/ftv2vertline.png \
    Box2D/Documentation/API/html/functions.html \
    Box2D/Documentation/API/html/functions_0x62.html \
    Box2D/Documentation/API/html/functions_0x63.html \
    Box2D/Documentation/API/html/functions_0x64.html \
    Box2D/Documentation/API/html/functions_0x65.html \
    Box2D/Documentation/API/html/functions_0x66.html \
    Box2D/Documentation/API/html/functions_0x67.html \
    Box2D/Documentation/API/html/functions_0x69.html \
    Box2D/Documentation/API/html/functions_0x6a.html \
    Box2D/Documentation/API/html/functions_0x6b.html \
    Box2D/Documentation/API/html/functions_0x6c.html \
    Box2D/Documentation/API/html/functions_0x6d.html \
    Box2D/Documentation/API/html/functions_0x6e.html \
    Box2D/Documentation/API/html/functions_0x6f.html \
    Box2D/Documentation/API/html/functions_0x70.html \
    Box2D/Documentation/API/html/functions_0x71.html \
    Box2D/Documentation/API/html/functions_0x72.html \
    Box2D/Documentation/API/html/functions_0x73.html \
    Box2D/Documentation/API/html/functions_0x74.html \
    Box2D/Documentation/API/html/functions_0x75.html \
    Box2D/Documentation/API/html/functions_0x76.html \
    Box2D/Documentation/API/html/functions_0x7e.html \
    Box2D/Documentation/API/html/functions_eval.html \
    Box2D/Documentation/API/html/functions_func.html \
    Box2D/Documentation/API/html/functions_func_0x62.html \
    Box2D/Documentation/API/html/functions_func_0x63.html \
    Box2D/Documentation/API/html/functions_func_0x64.html \
    Box2D/Documentation/API/html/functions_func_0x65.html \
    Box2D/Documentation/API/html/functions_func_0x66.html \
    Box2D/Documentation/API/html/functions_func_0x67.html \
    Box2D/Documentation/API/html/functions_func_0x69.html \
    Box2D/Documentation/API/html/functions_func_0x6c.html \
    Box2D/Documentation/API/html/functions_func_0x6d.html \
    Box2D/Documentation/API/html/functions_func_0x6e.html \
    Box2D/Documentation/API/html/functions_func_0x6f.html \
    Box2D/Documentation/API/html/functions_func_0x70.html \
    Box2D/Documentation/API/html/functions_func_0x71.html \
    Box2D/Documentation/API/html/functions_func_0x72.html \
    Box2D/Documentation/API/html/functions_func_0x73.html \
    Box2D/Documentation/API/html/functions_func_0x74.html \
    Box2D/Documentation/API/html/functions_func_0x75.html \
    Box2D/Documentation/API/html/functions_func_0x76.html \
    Box2D/Documentation/API/html/functions_func_0x7e.html \
    Box2D/Documentation/API/html/functions_vars.html \
    Box2D/Documentation/API/html/globals.html \
    Box2D/Documentation/API/html/globals_defs.html \
    Box2D/Documentation/API/html/globals_enum.html \
    Box2D/Documentation/API/html/globals_eval.html \
    Box2D/Documentation/API/html/globals_func.html \
    Box2D/Documentation/API/html/globals_vars.html \
    Box2D/Documentation/API/html/hierarchy.html \
    Box2D/Documentation/API/html/index.html \
    Box2D/Documentation/API/html/jquery.js \
    Box2D/Documentation/API/html/nav_f.png \
    Box2D/Documentation/API/html/nav_g.png \
    Box2D/Documentation/API/html/nav_h.png \
    Box2D/Documentation/API/html/open.png \
    Box2D/Documentation/API/html/search/all_61.html \
    Box2D/Documentation/API/html/search/all_61.js \
    Box2D/Documentation/API/html/search/all_62.html \
    Box2D/Documentation/API/html/search/all_62.js \
    Box2D/Documentation/API/html/search/all_63.html \
    Box2D/Documentation/API/html/search/all_63.js \
    Box2D/Documentation/API/html/search/all_64.html \
    Box2D/Documentation/API/html/search/all_64.js \
    Box2D/Documentation/API/html/search/all_65.html \
    Box2D/Documentation/API/html/search/all_65.js \
    Box2D/Documentation/API/html/search/all_66.html \
    Box2D/Documentation/API/html/search/all_66.js \
    Box2D/Documentation/API/html/search/all_67.html \
    Box2D/Documentation/API/html/search/all_67.js \
    Box2D/Documentation/API/html/search/all_69.html \
    Box2D/Documentation/API/html/search/all_69.js \
    Box2D/Documentation/API/html/search/all_6a.html \
    Box2D/Documentation/API/html/search/all_6a.js \
    Box2D/Documentation/API/html/search/all_6b.html \
    Box2D/Documentation/API/html/search/all_6b.js \
    Box2D/Documentation/API/html/search/all_6c.html \
    Box2D/Documentation/API/html/search/all_6c.js \
    Box2D/Documentation/API/html/search/all_6d.html \
    Box2D/Documentation/API/html/search/all_6d.js \
    Box2D/Documentation/API/html/search/all_6e.html \
    Box2D/Documentation/API/html/search/all_6e.js \
    Box2D/Documentation/API/html/search/all_6f.html \
    Box2D/Documentation/API/html/search/all_6f.js \
    Box2D/Documentation/API/html/search/all_70.html \
    Box2D/Documentation/API/html/search/all_70.js \
    Box2D/Documentation/API/html/search/all_71.html \
    Box2D/Documentation/API/html/search/all_71.js \
    Box2D/Documentation/API/html/search/all_72.html \
    Box2D/Documentation/API/html/search/all_72.js \
    Box2D/Documentation/API/html/search/all_73.html \
    Box2D/Documentation/API/html/search/all_73.js \
    Box2D/Documentation/API/html/search/all_74.html \
    Box2D/Documentation/API/html/search/all_74.js \
    Box2D/Documentation/API/html/search/all_75.html \
    Box2D/Documentation/API/html/search/all_75.js \
    Box2D/Documentation/API/html/search/all_76.html \
    Box2D/Documentation/API/html/search/all_76.js \
    Box2D/Documentation/API/html/search/all_7e.html \
    Box2D/Documentation/API/html/search/all_7e.js \
    Box2D/Documentation/API/html/search/classes_62.html \
    Box2D/Documentation/API/html/search/classes_62.js \
    Box2D/Documentation/API/html/search/close.png \
    Box2D/Documentation/API/html/search/defines_62.html \
    Box2D/Documentation/API/html/search/defines_62.js \
    Box2D/Documentation/API/html/search/enums_62.html \
    Box2D/Documentation/API/html/search/enums_62.js \
    Box2D/Documentation/API/html/search/enumvalues_62.html \
    Box2D/Documentation/API/html/search/enumvalues_62.js \
    Box2D/Documentation/API/html/search/enumvalues_65.html \
    Box2D/Documentation/API/html/search/enumvalues_65.js \
    Box2D/Documentation/API/html/search/files_62.html \
    Box2D/Documentation/API/html/search/files_62.js \
    Box2D/Documentation/API/html/search/functions_61.html \
    Box2D/Documentation/API/html/search/functions_61.js \
    Box2D/Documentation/API/html/search/functions_62.html \
    Box2D/Documentation/API/html/search/functions_62.js \
    Box2D/Documentation/API/html/search/functions_63.html \
    Box2D/Documentation/API/html/search/functions_63.js \
    Box2D/Documentation/API/html/search/functions_64.html \
    Box2D/Documentation/API/html/search/functions_64.js \
    Box2D/Documentation/API/html/search/functions_65.html \
    Box2D/Documentation/API/html/search/functions_65.js \
    Box2D/Documentation/API/html/search/functions_66.html \
    Box2D/Documentation/API/html/search/functions_66.js \
    Box2D/Documentation/API/html/search/functions_67.html \
    Box2D/Documentation/API/html/search/functions_67.js \
    Box2D/Documentation/API/html/search/functions_69.html \
    Box2D/Documentation/API/html/search/functions_69.js \
    Box2D/Documentation/API/html/search/functions_6c.html \
    Box2D/Documentation/API/html/search/functions_6c.js \
    Box2D/Documentation/API/html/search/functions_6d.html \
    Box2D/Documentation/API/html/search/functions_6d.js \
    Box2D/Documentation/API/html/search/functions_6e.html \
    Box2D/Documentation/API/html/search/functions_6e.js \
    Box2D/Documentation/API/html/search/functions_6f.html \
    Box2D/Documentation/API/html/search/functions_6f.js \
    Box2D/Documentation/API/html/search/functions_70.html \
    Box2D/Documentation/API/html/search/functions_70.js \
    Box2D/Documentation/API/html/search/functions_71.html \
    Box2D/Documentation/API/html/search/functions_71.js \
    Box2D/Documentation/API/html/search/functions_72.html \
    Box2D/Documentation/API/html/search/functions_72.js \
    Box2D/Documentation/API/html/search/functions_73.html \
    Box2D/Documentation/API/html/search/functions_73.js \
    Box2D/Documentation/API/html/search/functions_74.html \
    Box2D/Documentation/API/html/search/functions_74.js \
    Box2D/Documentation/API/html/search/functions_75.html \
    Box2D/Documentation/API/html/search/functions_75.js \
    Box2D/Documentation/API/html/search/functions_76.html \
    Box2D/Documentation/API/html/search/functions_76.js \
    Box2D/Documentation/API/html/search/functions_7e.html \
    Box2D/Documentation/API/html/search/functions_7e.js \
    Box2D/Documentation/API/html/search/mag_sel.png \
    Box2D/Documentation/API/html/search/nomatches.html \
    Box2D/Documentation/API/html/search/pages_62.html \
    Box2D/Documentation/API/html/search/pages_62.js \
    Box2D/Documentation/API/html/search/search.css \
    Box2D/Documentation/API/html/search/search.js \
    Box2D/Documentation/API/html/search/search_l.png \
    Box2D/Documentation/API/html/search/search_m.png \
    Box2D/Documentation/API/html/search/search_r.png \
    Box2D/Documentation/API/html/search/variables_61.html \
    Box2D/Documentation/API/html/search/variables_61.js \
    Box2D/Documentation/API/html/search/variables_62.html \
    Box2D/Documentation/API/html/search/variables_62.js \
    Box2D/Documentation/API/html/search/variables_63.html \
    Box2D/Documentation/API/html/search/variables_63.js \
    Box2D/Documentation/API/html/search/variables_64.html \
    Box2D/Documentation/API/html/search/variables_64.js \
    Box2D/Documentation/API/html/search/variables_65.html \
    Box2D/Documentation/API/html/search/variables_65.js \
    Box2D/Documentation/API/html/search/variables_66.html \
    Box2D/Documentation/API/html/search/variables_66.js \
    Box2D/Documentation/API/html/search/variables_67.html \
    Box2D/Documentation/API/html/search/variables_67.js \
    Box2D/Documentation/API/html/search/variables_69.html \
    Box2D/Documentation/API/html/search/variables_69.js \
    Box2D/Documentation/API/html/search/variables_6a.html \
    Box2D/Documentation/API/html/search/variables_6a.js \
    Box2D/Documentation/API/html/search/variables_6b.html \
    Box2D/Documentation/API/html/search/variables_6b.js \
    Box2D/Documentation/API/html/search/variables_6c.html \
    Box2D/Documentation/API/html/search/variables_6c.js \
    Box2D/Documentation/API/html/search/variables_6d.html \
    Box2D/Documentation/API/html/search/variables_6d.js \
    Box2D/Documentation/API/html/search/variables_6e.html \
    Box2D/Documentation/API/html/search/variables_6e.js \
    Box2D/Documentation/API/html/search/variables_6f.html \
    Box2D/Documentation/API/html/search/variables_6f.js \
    Box2D/Documentation/API/html/search/variables_70.html \
    Box2D/Documentation/API/html/search/variables_70.js \
    Box2D/Documentation/API/html/search/variables_72.html \
    Box2D/Documentation/API/html/search/variables_72.js \
    Box2D/Documentation/API/html/search/variables_73.html \
    Box2D/Documentation/API/html/search/variables_73.js \
    Box2D/Documentation/API/html/search/variables_74.html \
    Box2D/Documentation/API/html/search/variables_74.js \
    Box2D/Documentation/API/html/search/variables_75.html \
    Box2D/Documentation/API/html/search/variables_75.js \
    Box2D/Documentation/API/html/structb2_a_a_b_b-members.html \
    Box2D/Documentation/API/html/structb2_a_a_b_b.html \
    Box2D/Documentation/API/html/structb2_block-members.html \
    Box2D/Documentation/API/html/structb2_block.html \
    Box2D/Documentation/API/html/structb2_body_def-members.html \
    Box2D/Documentation/API/html/structb2_body_def.html \
    Box2D/Documentation/API/html/structb2_chunk-members.html \
    Box2D/Documentation/API/html/structb2_chunk.html \
    Box2D/Documentation/API/html/structb2_clip_vertex-members.html \
    Box2D/Documentation/API/html/structb2_clip_vertex.html \
    Box2D/Documentation/API/html/structb2_color-members.html \
    Box2D/Documentation/API/html/structb2_color.html \
    Box2D/Documentation/API/html/structb2_contact_edge-members.html \
    Box2D/Documentation/API/html/structb2_contact_edge.html \
    Box2D/Documentation/API/html/structb2_contact_feature-members.html \
    Box2D/Documentation/API/html/structb2_contact_feature.html \
    Box2D/Documentation/API/html/structb2_contact_impulse-members.html \
    Box2D/Documentation/API/html/structb2_contact_impulse.html \
    Box2D/Documentation/API/html/structb2_contact_position_constraint-members.html \
    Box2D/Documentation/API/html/structb2_contact_position_constraint.html \
    Box2D/Documentation/API/html/structb2_contact_register-members.html \
    Box2D/Documentation/API/html/structb2_contact_register.html \
    Box2D/Documentation/API/html/structb2_contact_solver_def-members.html \
    Box2D/Documentation/API/html/structb2_contact_solver_def.html \
    Box2D/Documentation/API/html/structb2_contact_velocity_constraint-members.html \
    Box2D/Documentation/API/html/structb2_contact_velocity_constraint.html \
    Box2D/Documentation/API/html/structb2_distance_input-members.html \
    Box2D/Documentation/API/html/structb2_distance_input.html \
    Box2D/Documentation/API/html/structb2_distance_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_distance_joint_def.html \
    Box2D/Documentation/API/html/structb2_distance_joint_def.png \
    Box2D/Documentation/API/html/structb2_distance_output-members.html \
    Box2D/Documentation/API/html/structb2_distance_output.html \
    Box2D/Documentation/API/html/structb2_distance_proxy-members.html \
    Box2D/Documentation/API/html/structb2_distance_proxy.html \
    Box2D/Documentation/API/html/structb2_e_p_axis-members.html \
    Box2D/Documentation/API/html/structb2_e_p_axis.html \
    Box2D/Documentation/API/html/structb2_e_p_collider-members.html \
    Box2D/Documentation/API/html/structb2_e_p_collider.html \
    Box2D/Documentation/API/html/structb2_filter-members.html \
    Box2D/Documentation/API/html/structb2_filter.html \
    Box2D/Documentation/API/html/structb2_fixture_def-members.html \
    Box2D/Documentation/API/html/structb2_fixture_def.html \
    Box2D/Documentation/API/html/structb2_fixture_proxy-members.html \
    Box2D/Documentation/API/html/structb2_fixture_proxy.html \
    Box2D/Documentation/API/html/structb2_friction_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_friction_joint_def.html \
    Box2D/Documentation/API/html/structb2_friction_joint_def.png \
    Box2D/Documentation/API/html/structb2_gear_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_gear_joint_def.html \
    Box2D/Documentation/API/html/structb2_gear_joint_def.png \
    Box2D/Documentation/API/html/structb2_jacobian-members.html \
    Box2D/Documentation/API/html/structb2_jacobian.html \
    Box2D/Documentation/API/html/structb2_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_joint_def.html \
    Box2D/Documentation/API/html/structb2_joint_def.png \
    Box2D/Documentation/API/html/structb2_joint_edge-members.html \
    Box2D/Documentation/API/html/structb2_joint_edge.html \
    Box2D/Documentation/API/html/structb2_manifold-members.html \
    Box2D/Documentation/API/html/structb2_manifold.html \
    Box2D/Documentation/API/html/structb2_manifold_point-members.html \
    Box2D/Documentation/API/html/structb2_manifold_point.html \
    Box2D/Documentation/API/html/structb2_mass_data-members.html \
    Box2D/Documentation/API/html/structb2_mass_data.html \
    Box2D/Documentation/API/html/structb2_mat22-members.html \
    Box2D/Documentation/API/html/structb2_mat22.html \
    Box2D/Documentation/API/html/structb2_mat33-members.html \
    Box2D/Documentation/API/html/structb2_mat33.html \
    Box2D/Documentation/API/html/structb2_motor_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_motor_joint_def.html \
    Box2D/Documentation/API/html/structb2_motor_joint_def.png \
    Box2D/Documentation/API/html/structb2_mouse_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_mouse_joint_def.html \
    Box2D/Documentation/API/html/structb2_mouse_joint_def.png \
    Box2D/Documentation/API/html/structb2_pair-members.html \
    Box2D/Documentation/API/html/structb2_pair.html \
    Box2D/Documentation/API/html/structb2_position-members.html \
    Box2D/Documentation/API/html/structb2_position.html \
    Box2D/Documentation/API/html/structb2_position_solver_manifold-members.html \
    Box2D/Documentation/API/html/structb2_position_solver_manifold.html \
    Box2D/Documentation/API/html/structb2_prismatic_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_prismatic_joint_def.html \
    Box2D/Documentation/API/html/structb2_prismatic_joint_def.png \
    Box2D/Documentation/API/html/structb2_profile-members.html \
    Box2D/Documentation/API/html/structb2_profile.html \
    Box2D/Documentation/API/html/structb2_pulley_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_pulley_joint_def.html \
    Box2D/Documentation/API/html/structb2_pulley_joint_def.png \
    Box2D/Documentation/API/html/structb2_ray_cast_input-members.html \
    Box2D/Documentation/API/html/structb2_ray_cast_input.html \
    Box2D/Documentation/API/html/structb2_ray_cast_output-members.html \
    Box2D/Documentation/API/html/structb2_ray_cast_output.html \
    Box2D/Documentation/API/html/structb2_reference_face-members.html \
    Box2D/Documentation/API/html/structb2_reference_face.html \
    Box2D/Documentation/API/html/structb2_revolute_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_revolute_joint_def.html \
    Box2D/Documentation/API/html/structb2_revolute_joint_def.png \
    Box2D/Documentation/API/html/structb2_rope_def-members.html \
    Box2D/Documentation/API/html/structb2_rope_def.html \
    Box2D/Documentation/API/html/structb2_rope_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_rope_joint_def.html \
    Box2D/Documentation/API/html/structb2_rope_joint_def.png \
    Box2D/Documentation/API/html/structb2_rot-members.html \
    Box2D/Documentation/API/html/structb2_rot.html \
    Box2D/Documentation/API/html/structb2_separation_function-members.html \
    Box2D/Documentation/API/html/structb2_separation_function.html \
    Box2D/Documentation/API/html/structb2_simplex-members.html \
    Box2D/Documentation/API/html/structb2_simplex.html \
    Box2D/Documentation/API/html/structb2_simplex_cache-members.html \
    Box2D/Documentation/API/html/structb2_simplex_cache.html \
    Box2D/Documentation/API/html/structb2_simplex_vertex-members.html \
    Box2D/Documentation/API/html/structb2_simplex_vertex.html \
    Box2D/Documentation/API/html/structb2_solver_data-members.html \
    Box2D/Documentation/API/html/structb2_solver_data.html \
    Box2D/Documentation/API/html/structb2_stack_entry-members.html \
    Box2D/Documentation/API/html/structb2_stack_entry.html \
    Box2D/Documentation/API/html/structb2_sweep-members.html \
    Box2D/Documentation/API/html/structb2_sweep.html \
    Box2D/Documentation/API/html/structb2_t_o_i_input-members.html \
    Box2D/Documentation/API/html/structb2_t_o_i_input.html \
    Box2D/Documentation/API/html/structb2_t_o_i_output-members.html \
    Box2D/Documentation/API/html/structb2_t_o_i_output.html \
    Box2D/Documentation/API/html/structb2_temp_polygon-members.html \
    Box2D/Documentation/API/html/structb2_temp_polygon.html \
    Box2D/Documentation/API/html/structb2_time_step-members.html \
    Box2D/Documentation/API/html/structb2_time_step.html \
    Box2D/Documentation/API/html/structb2_transform-members.html \
    Box2D/Documentation/API/html/structb2_transform.html \
    Box2D/Documentation/API/html/structb2_tree_node-members.html \
    Box2D/Documentation/API/html/structb2_tree_node.html \
    Box2D/Documentation/API/html/structb2_vec2-members.html \
    Box2D/Documentation/API/html/structb2_vec2.html \
    Box2D/Documentation/API/html/structb2_vec3-members.html \
    Box2D/Documentation/API/html/structb2_vec3.html \
    Box2D/Documentation/API/html/structb2_velocity-members.html \
    Box2D/Documentation/API/html/structb2_velocity.html \
    Box2D/Documentation/API/html/structb2_velocity_constraint_point-members.html \
    Box2D/Documentation/API/html/structb2_velocity_constraint_point.html \
    Box2D/Documentation/API/html/structb2_version-members.html \
    Box2D/Documentation/API/html/structb2_version.html \
    Box2D/Documentation/API/html/structb2_weld_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_weld_joint_def.html \
    Box2D/Documentation/API/html/structb2_weld_joint_def.png \
    Box2D/Documentation/API/html/structb2_wheel_joint_def-members.html \
    Box2D/Documentation/API/html/structb2_wheel_joint_def.html \
    Box2D/Documentation/API/html/structb2_wheel_joint_def.png \
    Box2D/Documentation/API/html/structb2_world_manifold-members.html \
    Box2D/Documentation/API/html/structb2_world_manifold.html \
    Box2D/Documentation/API/html/structb2_world_query_wrapper-members.html \
    Box2D/Documentation/API/html/structb2_world_query_wrapper.html \
    Box2D/Documentation/API/html/structb2_world_ray_cast_wrapper-members.html \
    Box2D/Documentation/API/html/structb2_world_ray_cast_wrapper.html \
    Box2D/Documentation/API/html/sync_off.png \
    Box2D/Documentation/API/html/sync_on.png \
    Box2D/Documentation/API/html/tab_a.png \
    Box2D/Documentation/API/html/tab_b.png \
    Box2D/Documentation/API/html/tab_h.png \
    Box2D/Documentation/API/html/tab_s.png \
    Box2D/Documentation/API/html/tabs.css \
    Box2D/Documentation/API/html/unionb2_contact_i_d-members.html \
    Box2D/Documentation/API/html/unionb2_contact_i_d.html \
    Box2D/Documentation/Doxyfile \
    Box2D/Documentation/images/Chain1.png \
    Box2D/Documentation/images/Chain1.svg \
    Box2D/Documentation/images/DebugDraw.png \
    Box2D/Documentation/images/GhostCollision.png \
    Box2D/Documentation/images/GhostCollision.svg \
    Box2D/Documentation/images/GhostVertices.png \
    Box2D/Documentation/images/GhostVertices.svg \
    Box2D/Documentation/images/SelfIntersect.png \
    Box2D/Documentation/images/SelfIntersect.svg \
    Box2D/Documentation/images/SkinCollision.png \
    Box2D/Documentation/images/SkinCollision.svg \
    Box2D/Documentation/images/SkinnedPolygon.png \
    Box2D/Documentation/images/SkinnedPolygon.svg \
    Box2D/Documentation/images/Tunnel1.png \
    Box2D/Documentation/images/Tunnel1.svg \
    Box2D/Documentation/images/WheelJoint.png \
    Box2D/Documentation/images/WheelJoint.svg \
    Box2D/Documentation/images/bodyOrigin.gif \
    Box2D/Documentation/images/captured.png \
    Box2D/Documentation/images/captured.svg \
    Box2D/Documentation/images/convex_concave.gif \
    Box2D/Documentation/images/distance.png \
    Box2D/Documentation/images/distance.svg \
    Box2D/Documentation/images/distanceJoint.gif \
    Box2D/Documentation/images/gearJoint.gif \
    Box2D/Documentation/images/manifolds.png \
    Box2D/Documentation/images/manifolds.svg \
    Box2D/Documentation/images/missed.png \
    Box2D/Documentation/images/missed.svg \
    Box2D/Documentation/images/modules.png \
    Box2D/Documentation/images/modules.svg \
    Box2D/Documentation/images/prismaticJoint.gif \
    Box2D/Documentation/images/pulleyJoint.gif \
    Box2D/Documentation/images/raycast.png \
    Box2D/Documentation/images/raycast.svg \
    Box2D/Documentation/images/regionquery.png \
    Box2D/Documentation/images/regionquery.svg \
    Box2D/Documentation/images/revoluteJoint.gif \
    Box2D/Documentation/images/testbed.gif \
    Box2D/Documentation/images/tunneling.png \
    Box2D/Documentation/images/tunneling.svg \
    Box2D/Documentation/images/winding.png \
    Box2D/Documentation/images/winding.svg \
    Box2D/Documentation/manual.docx \
    Box2D/Documentation/manual.pdf \
    Box2D/HelloWorld/CMakeLists.txt \
    Box2D/License.txt \
    Box2D/Readme.txt \
    Box2D/Testbed/CMakeLists.txt \
    Box2D/freeglut/CMakeLists.txt \
    Box2D/freeglut/COPYING \
    Box2D/glui/CMakeLists.txt \
    Box2D/glui/readme.txt \
    Box2D/premake4.lua
